---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-edge
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-edge
  type: {{ .Values.edge.serviceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-edge
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-edge
  template:
    metadata:
      name: todos-edge
      labels:
        app: todos-edge
    spec:
      containers:
      - image: {{ .Values.registry }}/todos-edge:latest
        name: todos-edge
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: TODOS_API_ENDPOINT
          value: "http://todos-api:8080"
        - name: TODOS_UI_ENDPOINT
          value: "http://todos-webui:8080"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080