---
apiVersion: v1
kind: Service
metadata:
  name: todos-webui
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-webui
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-webui
  type: {{ .Values.webui.serviceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-webui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-webui
  template:
    metadata:
      name: todos-webui
      labels:
        app: todos-webui
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-webui:latest
          name: todos-webui
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080