---
apiVersion: v1
kind: Service
metadata:
  name: todos-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-postgres
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-redis
  type: {{ .Values.postgres.serviceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-postgres
  template:
    metadata:
      name: todos-postgres
      labels:
        app: todos-postgres
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-postgres:{{ .Values.version }}
          name: todos-postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.postgres.pwd }}"