---
apiVersion: v1
kind: Service
metadata:
  name: todos-admin
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-admin
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-admin
  type: {{ .Values.admin.serviceType }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-admin
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-admin
  template:
    metadata:
      name: todos-admin
      labels:
        app: todos-admin
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-admin:{{ .Values.version }}
          name: todos-admin
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
