---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgconfig
  namespace: {{ .Values.namespace }}
  labels:
    app: Postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.pwd }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: tcp-postgres
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-v1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: "postgres"
  selector:
    matchLabels:
      app: postgres
      version: v1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        version: v1
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
        - configMapRef:
            name: pgconfig


# ## this will persist the data of the Postgres database
# volumeMounts:
# - name: ordb
# mountPath: /var/lib/PostgreSQL/data
# subPath: Postgres
# volumeClaimTemplates:
# - metadata:
# name: ordb
# spec:
# accessModes: [ "ReadWriteOnce" ]
# storageClassName: gp2
# resources:
# requests:
# storage: 3Gi