---
apiVersion: v1
kind: Service
metadata:
  name: todos-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-redis
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-redis
  type: {{ .Values.redis.serviceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis-v1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-redis
      version: v1
  template:
    metadata:
      name: todos-redis
      namespace: todos
      labels:
        app: todos-redis
        version: v1
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-redis-mesh:latest
          name: todos-redis
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

