---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-api
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: todos-api
  type: {{ .Values.api.serviceType }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-v1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
      version: v1
  template:
    metadata:
      name: todos-api
      labels:
        app: todos-api
        version: v1
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-api-mesh:latest
          name: todos-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-v2
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
      version: v2
  template:
    metadata:
      name: todos-api
      labels:
        app: todos-api
        version: v2
    spec:
      containers:
        - image: {{ .Values.registry }}/todos-api-mesh:latest
          name: todos-api
          imagePullPolicy: Always
          env:
          - name: TODOS_API_UPPER
            value: "true"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080