eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://todos-registry:8761/eureka/
# zuul:
#   routes:
#     ui:
#       path: /**
#       url:  ${todos.ui.endpoint}
#       stripPrefix: false
#     api:
#       path: /todos/**
#       url:  ${todos.api.endpoint}
#       stripPrefix: true
spring:
  application:
    name: todos-edge
  cloud:
    gateway:
      routes:
      - id: todos_all_api
        uri: lb://todos-api
        predicates:
        - Path=/todos/**
        filters:
        - SetResponseHeader=X-TODOS-CLOUD-GATEWAY-ROUTE-ID, todos_all_api
        - RewritePath=/todos/(?<path>.*), /$\{path}
      - id: todos_ui_root
        uri: lb://todos-webui
        predicates:
        - Path=/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  http:
    client:
      enabled: false
